// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP3NR9XytaGU1lX2HVvQw4BeL6G_ZOwgs',
    appId: '1:1061183235633:web:5a388ec8c9781f3b4e5710',
    messagingSenderId: '1061183235633',
    projectId: 'mgc-management',
    authDomain: 'mgc-management.firebaseapp.com',
    storageBucket: 'mgc-management.firebasestorage.app',
    measurementId: 'G-8W5MNMXBFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbFbal-HFex1mdJHYzvfspBCvauX_sLdg',
    appId: '1:1061183235633:android:a03cd9b40247804d4e5710',
    messagingSenderId: '1061183235633',
    projectId: 'mgc-management',
    storageBucket: 'mgc-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC95_p3AWdFfyh4geyEWewKT1rzJ2ApZA4',
    appId: '1:1061183235633:ios:9c5d817ef8b920ee4e5710',
    messagingSenderId: '1061183235633',
    projectId: 'mgc-management',
    storageBucket: 'mgc-management.firebasestorage.app',
    iosBundleId: 'com.example.one',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC95_p3AWdFfyh4geyEWewKT1rzJ2ApZA4',
    appId: '1:1061183235633:ios:9c5d817ef8b920ee4e5710',
    messagingSenderId: '1061183235633',
    projectId: 'mgc-management',
    storageBucket: 'mgc-management.firebasestorage.app',
    iosBundleId: 'com.example.one',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP3NR9XytaGU1lX2HVvQw4BeL6G_ZOwgs',
    appId: '1:1061183235633:web:2fd9a0b8a18fb1d84e5710',
    messagingSenderId: '1061183235633',
    projectId: 'mgc-management',
    authDomain: 'mgc-management.firebaseapp.com',
    storageBucket: 'mgc-management.firebasestorage.app',
    measurementId: 'G-922E1C2HW6',
  );

}